
development:
  adapter: sqlite3
  database: "db/spree_development.sqlite3"
test:
  adapter: sqlite3
  database: "db/spree_test.sqlite3"
production:
  adapter: sqlite3
  database: "db/spree_production.sqlite3"

